<?php

use Drupal\entity2\DIC\ServiceContainer;
use Drupal\entity2\Util\DumpUtil;
use Drupal\entity2\Wrapper\ListValue\BasicValueListWrapper;
use Drupal\entity2\Wrapper\ListValue\EntityReferenceListWrapper;
use Drupal\entity2\Wrapper\Value\SingleValueWrapperInterface;

/**
 * Dependency injection container
 *
 * @return ServiceContainer
 */
function entity2() {
  static $services;
  if (isset($services)) {
    return $services;
  }
  return $services = new ServiceContainer();
}
